// Dentistry profession module — defines its own credential types, governing bodies,
// continuing-education terminology, renewal rules, and professional opportunities.
// Additional profession modules (physicians, PAs, NPs, nurses, pharmacists, PT, OT, etc.)
// follow the same shape and register in src/professions/index.js.

import { stateNames } from "./stateNames";

export const dentistry = {
  key: "dentistry",
  label: "Dentistry",
  tagline: "Licensed dental professional",
  badge: "Flagship",
  // User-facing label for the backend `jurisdiction` field — dentistry uses "State".
  jurisdictionLabel: "State",
  stateNames,
  // Profession-specific credential types (NOT shared across professions)
  credentialTypes: [
    "State Dental License",
    "DEA Registration",
    "BLS Certification",
    "ACLS Certification",
    "PALS Certification",
    "CPR Certification",
    "Specialty Board Certification",
    "Malpractice / Professional Liability Insurance",
    "NPI Number",
    "DEA Waiver",
    "Sedation Permit",
    "Nitrous Oxide Permit",
  ],
  // Conservative explicit aliases for CV import credential-type normalization.
  // Keys are lowercase variants the LLM may produce; values map to the canonical
  // credential_type. Anything not listed here and not an exact canonical match
  // (case-insensitive) is dropped. No fuzzy/broad matching is performed.
  credentialTypeAliases: {
    "bls": "BLS Certification",
    "bls provider": "BLS Certification",
    "basic life support": "BLS Certification",
    "bls cert": "BLS Certification",
    "acls": "ACLS Certification",
    "acls provider": "ACLS Certification",
    "advanced cardiac life support": "ACLS Certification",
    "advanced cardiovascular life support": "ACLS Certification",
    "pals": "PALS Certification",
    "pals provider": "PALS Certification",
    "pediatric advanced life support": "PALS Certification",
    "cpr": "CPR Certification",
    "cpr course": "CPR Certification",
    "dea": "DEA Registration",
    "dea number": "DEA Registration",
    "dea registration number": "DEA Registration",
    "dental license": "State Dental License",
    "state license": "State Dental License",
    "npi": "NPI Number",
    "national provider identifier": "NPI Number",
    "board certification": "Specialty Board Certification",
    "board certified": "Specialty Board Certification",
    "diplomate": "Specialty Board Certification",
    "sedation license": "Sedation Permit",
    "sedation certification": "Sedation Permit",
    "moderate sedation permit": "Sedation Permit",
    "conscious sedation permit": "Sedation Permit",
    "nitrous oxide license": "Nitrous Oxide Permit",
    "nitrous oxide certification": "Nitrous Oxide Permit",
    "nitrous permit": "Nitrous Oxide Permit",
    "malpractice insurance": "Malpractice / Professional Liability Insurance",
    "professional liability insurance": "Malpractice / Professional Liability Insurance",
    "malpractice coverage": "Malpractice / Professional Liability Insurance",
    "liability insurance": "Malpractice / Professional Liability Insurance",
  },
  // First-class credential templates — pre-fill issuing body, description, and labels
  // when the user selects one of these critical credential types.
  credentialTemplates: {
    "State Dental License": {
      issuingBody: "State Board of Dentistry",
      cycleYears: 2,
      description: "State-issued license to practice dentistry.",
      numberLabel: "License Number",
      critical: true,
      requiresJurisdiction: true,
      nameTemplate: "{state} Dental License",
    },
    "DEA Registration": {
      issuingBody: "Drug Enforcement Administration (DEA)",
      cycleYears: 3,
      description: "Federal registration for prescribing controlled substances.",
      numberLabel: "DEA Registration Number",
      critical: true,
    },
    "Malpractice / Professional Liability Insurance": {
      issuingBody: "Insurance Carrier",
      cycleYears: 1,
      description: "Professional liability coverage — required by most employers and hospitals.",
      numberLabel: "Policy Number",
      critical: true,
    },
    "BLS Certification": {
      issuingBody: "American Heart Association",
      cycleYears: 2,
      description: "Basic Life Support — required for clinical practice.",
      numberLabel: "Certification ID",
      critical: true,
    },
    "ACLS Certification": {
      issuingBody: "American Heart Association",
      cycleYears: 2,
      description: "Advanced Cardiovascular Life Support.",
      numberLabel: "Certification ID",
      critical: true,
    },
    "PALS Certification": {
      issuingBody: "American Heart Association",
      cycleYears: 2,
      description: "Pediatric Advanced Life Support.",
      numberLabel: "Certification ID",
      critical: true,
    },
    "Sedation Permit": {
      issuingBody: "State Board of Dentistry",
      cycleYears: 2,
      description: "State permit for moderate/conscious sedation administration.",
      numberLabel: "Permit Number",
      critical: true,
      requiresJurisdiction: true,
      nameTemplate: "{state} Sedation Permit",
    },
    "Nitrous Oxide Permit": {
      issuingBody: "State Board of Dentistry",
      cycleYears: 2,
      description: "State permit for nitrous oxide administration.",
      numberLabel: "Permit Number",
      critical: true,
      requiresJurisdiction: true,
      nameTemplate: "{state} Nitrous Oxide Permit",
    },
    "Specialty Board Certification": {
      issuingBody: "Specialty Board",
      cycleYears: 10,
      description: "Board certification in a dental specialty — typically a 10-year cycle.",
      numberLabel: "Board Certificate Number",
      critical: true,
    },
  },
  // Issuing / governing bodies relevant to dentistry
  issuingBodies: [
    "State Board of Dentistry",
    "American Dental Association (ADA)",
    "Drug Enforcement Administration (DEA)",
    "American Board of Dental Specialties",
    "American Board of Pediatric Dentistry",
    "American Board of Orthodontics",
    "American Board of Endodontics",
    "American Board of Oral and Maxillofacial Surgery",
    "American Board of Periodontology",
    "American Board of Prosthodontics",
    "American Heart Association",
    "Joint Commission",
    "Specialty Board",
    "Insurance Carrier",
  ],
  // Dental specialties
  specialties: [
    "General Dentistry",
    "Orthodontics and Dentofacial Orthopedics",
    "Endodontics",
    "Oral and Maxillofacial Surgery",
    "Oral and Maxillofacial Radiology",
    "Oral and Maxillofacial Pathology",
    "Pediatric Dentistry",
    "Periodontics",
    "Prosthodontics",
    "Dental Public Health",
  ],
  // Career stage options for dentistry professionals
  careerStages: [
    "Pre-dental",
    "Dental student",
    "Resident / Fellow",
    "Practicing dentist",
    "Academic / Research",
    "Other",
  ],
  // Continuing education terminology specific to dentistry
  ce: {
    tabLabel: "CE",
    unitLabel: "CE hours",
    creditLabel: "CE credits",
    recordLabel: "Continuing Education Course",
    recordLabelPlural: "Continuing Education Courses",
    categories: [
      "Clinical / Didactic",
      "Practice Management",
      "Infection Control / OSHA",
      "Ethics & Jurisprudence",
      "Pharmacology",
      "Radiography",
      "CPR / BLS / ACLS",
      "Patient Safety",
      "Opioid / Pain Management",
      "Dental Materials",
    ],
    types: ["Lecture", "Hands-on Workshop", "Online Course", "Self-study", "Conference", "Webinar"],
    // Typical renewal expectations (informational; varies by state)
    typicalAnnualHours: 20,
    typicalCycleYears: 2,
  },
  // Canonical requirement keys for CE-to-compliance mapping (Model C).
  // Stable internal keys so CeApplicability links survive requirement label changes.
  // Mirrors base44/shared/requirementKeys.ts for frontend use.
  requirementKeys: {
    overall: "overall",
    categories: [
      { key: "clinical_didactic", label: "Clinical / Didactic" },
      { key: "practice_management", label: "Practice Management" },
      { key: "infection_control_osha", label: "Infection Control / OSHA" },
      { key: "ethics_jurisprudence", label: "Ethics & Jurisprudence" },
      { key: "pharmacology", label: "Pharmacology" },
      { key: "radiography", label: "Radiography" },
      { key: "cpr_bls_acls", label: "CPR / BLS / ACLS" },
      { key: "patient_safety", label: "Patient Safety" },
      { key: "opioid_pain_management", label: "Opioid / Pain Management" },
      { key: "dental_materials", label: "Dental Materials" },
    ],
    topics: [
      { key: "opioid_prescribing", label: "Opioid Prescribing" },
      { key: "infection_control", label: "Infection Control" },
      { key: "ethics", label: "Ethics" },
      { key: "jurisprudence", label: "Jurisprudence" },
      { key: "cpr", label: "CPR" },
      { key: "bls", label: "BLS" },
      { key: "pain_management", label: "Pain Management" },
      { key: "child_abuse_recognition", label: "Child Abuse Recognition" },
      { key: "domestic_violence", label: "Domestic Violence" },
      { key: "cultural_competency", label: "Cultural Competency" },
    ],
  },
  // Professional opportunities relevant to dentistry
  opportunityTypes: [
    "Associate Dentist",
    "Partner / Equity Track",
    "Practice Acquisition",
    "Locum Tenens",
    "Academic / Faculty",
    "Public Health",
    "Corporate / Industry",
    "Residency / GPR",
    "Fellowship (Specialty)",
    "Dental Service Organization (DSO)",
  ],
  // Renewal rules — informational defaults; each license record carries its own dates
  renewal: {
    licenseCycleYears: 2,
    deaCycleYears: 3,
    blsCycleYears: 2,
    aclsCycleYears: 2,
    note: "Renual cycles vary by state board. Each credential record stores its own expiration date and drives reminders.",
  },
  // US jurisdictions
  jurisdictions: [
    "AL","AK","AZ","AR","CA","CO","CT","DE","DC","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"
  ],
  membershipOrganizations: [
    "American Dental Association (ADA)",
    "Academy of General Dentistry (AGD)",
    "American Academy of Pediatric Dentistry (AAPD)",
    "American Association of Orthodontists (AAO)",
    "American Association of Endodontists (AAE)",
    "American College of Prosthodontists (ACP)",
    "American Academy of Periodontology (AAP)",
    "American Association of Oral and Maxillofacial Surgeons (AAOMS)",
    "State Dental Association",
    "Local Dental Society",
  ],
  educationDegrees: [
    "DDS",
    "DMD",
    "BDSc / BDS",
    "MS (Specialty)",
    "PhD",
    "AEGD / GPR Certificate",
    "BS",
    "BA",
    "AA / AS",
  ],
};