// Dentistry profession module — defines its own credential types, governing bodies,
// continuing-education terminology, renewal rules, and professional opportunities.
// Additional profession modules (physicians, PAs, NPs, nurses, pharmacists, PT, OT, etc.)
// follow the same shape and register in src/professions/index.js.

export const dentistry = {
  key: "dentistry",
  label: "Dentistry",
  tagline: "Licensed dental professional",
  badge: "Flagship",
  // Profession-specific credential types (NOT shared across professions)
  credentialTypes: [
    "Doctor of Dental Surgery (DDS)",
    "Doctor of Dental Medicine (DMD)",
    "State Dental License",
    "DEA Registration",
    "BLS Certification",
    "ACLS Certification",
    "PALS Certification",
    "CPR Certification",
    "Specialty Board Certification",
    "Malpractice / Professional Liability Insurance",
    "NPI Number",
    "DEA Waiver",
    "Sedation Permit",
    "Nitrous Oxide Permit",
  ],
  // First-class credential templates — pre-fill issuing body, description, and labels
  // when the user selects one of these critical credential types.
  credentialTemplates: {
    "State Dental License": {
      issuingBody: "State Board of Dentistry",
      cycleYears: 2,
      description: "State-issued license to practice dentistry.",
      numberLabel: "License Number",
      critical: true,
    },
    "DEA Registration": {
      issuingBody: "Drug Enforcement Administration (DEA)",
      cycleYears: 3,
      description: "Federal registration for prescribing controlled substances.",
      numberLabel: "DEA Registration Number",
      critical: true,
    },
    "Malpractice / Professional Liability Insurance": {
      issuingBody: "Insurance Carrier",
      cycleYears: 1,
      description: "Professional liability coverage — required by most employers and hospitals.",
      numberLabel: "Policy Number",
      critical: true,
    },
    "BLS Certification": {
      issuingBody: "American Heart Association",
      cycleYears: 2,
      description: "Basic Life Support — required for clinical practice.",
      numberLabel: "Certification ID",
      critical: true,
    },
    "ACLS Certification": {
      issuingBody: "American Heart Association",
      cycleYears: 2,
      description: "Advanced Cardiovascular Life Support.",
      numberLabel: "Certification ID",
      critical: true,
    },
    "PALS Certification": {
      issuingBody: "American Heart Association",
      cycleYears: 2,
      description: "Pediatric Advanced Life Support.",
      numberLabel: "Certification ID",
      critical: true,
    },
    "Sedation Permit": {
      issuingBody: "State Board of Dentistry",
      cycleYears: 2,
      description: "State permit for moderate/conscious sedation administration.",
      numberLabel: "Permit Number",
      critical: true,
    },
    "Nitrous Oxide Permit": {
      issuingBody: "State Board of Dentistry",
      cycleYears: 2,
      description: "State permit for nitrous oxide administration.",
      numberLabel: "Permit Number",
      critical: true,
    },
    "Specialty Board Certification": {
      issuingBody: "Specialty Board",
      cycleYears: 10,
      description: "Board certification in a dental specialty — typically a 10-year cycle.",
      numberLabel: "Board Certificate Number",
      critical: true,
    },
  },
  // Issuing / governing bodies relevant to dentistry
  issuingBodies: [
    "State Board of Dentistry",
    "American Dental Association (ADA)",
    "Drug Enforcement Administration (DEA)",
    "American Board of Dental Specialties",
    "American Board of Pediatric Dentistry",
    "American Board of Orthodontics",
    "American Board of Endodontics",
    "American Board of Oral and Maxillofacial Surgery",
    "American Board of Periodontology",
    "American Board of Prosthodontics",
    "American Heart Association",
    "Joint Commission",
    "Specialty Board",
    "Insurance Carrier",
  ],
  // Dental specialties
  specialties: [
    "General Dentistry",
    "Orthodontics and Dentofacial Orthopedics",
    "Endodontics",
    "Oral and Maxillofacial Surgery",
    "Oral and Maxillofacial Radiology",
    "Oral and Maxillofacial Pathology",
    "Pediatric Dentistry",
    "Periodontics",
    "Prosthodontics",
    "Dental Public Health",
  ],
  // Continuing education terminology specific to dentistry
  ce: {
    unitLabel: "CE hours",
    creditLabel: "CE credits",
    recordLabel: "Continuing Education Course",
    recordLabelPlural: "Continuing Education Courses",
    categories: [
      "Clinical / Didactic",
      "Practice Management",
      "Infection Control / OSHA",
      "Ethics & Jurisprudence",
      "Pharmacology",
      "Radiography",
      "CPR / BLS / ACLS",
      "Patient Safety",
      "Opioid / Pain Management",
      "Dental Materials",
    ],
    types: ["Lecture", "Hands-on Workshop", "Online Course", "Self-study", "Conference", "Webinar"],
    // Typical renewal expectations (informational; varies by state)
    typicalAnnualHours: 20,
    typicalCycleYears: 2,
  },
  // Professional opportunities relevant to dentistry
  opportunityTypes: [
    "Associate Dentist",
    "Partner / Equity Track",
    "Practice Acquisition",
    "Locum Tenens",
    "Academic / Faculty",
    "Public Health",
    "Corporate / Industry",
    "Residency / GPR",
    "Fellowship (Specialty)",
    "Dental Service Organization (DSO)",
  ],
  // Renewal rules — informational defaults; each license record carries its own dates
  renewal: {
    licenseCycleYears: 2,
    deaCycleYears: 3,
    blsCycleYears: 2,
    aclsCycleYears: 2,
    note: "Renual cycles vary by state board. Each credential record stores its own expiration date and drives reminders.",
  },
  // US jurisdictions
  jurisdictions: [
    "AL","AK","AZ","AR","CA","CO","CT","DE","DC","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"
  ],
  membershipOrganizations: [
    "American Dental Association (ADA)",
    "Academy of General Dentistry (AGD)",
    "American Academy of Pediatric Dentistry (AAPD)",
    "American Association of Orthodontists (AAO)",
    "American Association of Endodontists (AAE)",
    "American College of Prosthodontists (ACP)",
    "American Academy of Periodontology (AAP)",
    "American Association of Oral and Maxillofacial Surgeons (AAOMS)",
    "State Dental Association",
    "Local Dental Society",
  ],
  educationDegrees: [
    "DDS",
    "DMD",
    "BDSc / BDS",
    "MS (Specialty)",
    "PhD",
    "AEGD / GPR Certificate",
    "BS",
    "BA",
    "AA / AS",
  ],
};