// Medicine (MD/DO) profession module — lightweight proof-of-concept alongside the
// fully built Dentistry flagship. Same shape as dentistry.js so the shared,
// profession-agnostic core (career memory, Ask My Career, Career Lens, opportunities,
// reminders, documents) works unchanged. Only the profession-specific terminology
// differs: credential types, governing boards, CME terminology, specialties, and
// opportunity categories.

export const medicine = {
  key: "medicine",
  label: "Medicine",
  tagline: "Licensed physician (MD/DO)",
  badge: "Proof-of-concept",
  credentialTypes: [
    "Doctor of Medicine (MD)",
    "Doctor of Osteopathic Medicine (DO)",
    "State Medical License",
    "DEA Registration",
    "BLS Certification",
    "ACLS Certification",
    "PALS Certification",
    "ATLS Certification",
    "Board Certification (ABMS)",
    "Board Eligible",
    "NPI Number",
    "Controlled Substance Registration",
    "Malpractice / Professional Liability Insurance",
  ],
  issuingBodies: [
    "State Board of Medicine",
    "State Medical Board",
    "American Medical Association (AMA)",
    "American Osteopathic Association (AOA)",
    "Drug Enforcement Administration (DEA)",
    "American Board of Medical Specialties (ABMS)",
    "American Board of Internal Medicine (ABIM)",
    "American Board of Family Medicine (ABFM)",
    "American Board of Pediatrics (ABP)",
    "American Board of Surgery (ABS)",
    "American Board of Emergency Medicine (ABEM)",
    "American Board of Anesthesiology",
    "American Board of Psychiatry and Neurology",
    "Federation of State Medical Boards (FSMB)",
    "American Heart Association",
    "Joint Commission",
    "Insurance Carrier",
  ],
  specialties: [
    "Internal Medicine",
    "Family Medicine",
    "Pediatrics",
    "Emergency Medicine",
    "Anesthesiology",
    "Surgery — General",
    "Orthopedic Surgery",
    "Cardiology",
    "Dermatology",
    "Neurology",
    "Obstetrics & Gynecology",
    "Psychiatry",
    "Radiology",
    "Pathology",
    "Ophthalmology",
    "Otolaryngology",
    "Urology",
    "Physical Medicine & Rehabilitation",
  ],
  ce: {
    unitLabel: "CME credits",
    creditLabel: "AMA PRA Category 1 Credits",
    recordLabel: "CME Activity",
    recordLabelPlural: "CME Activities",
    categories: [
      "AMA PRA Category 1",
      "AMA PRA Category 2",
      "Patient Safety",
      "Opioid Prescribing / Pain Management",
      "Medical Ethics",
      "Risk Management",
      "Cultural Competency",
      "Implicit Bias",
      "Suicide Prevention",
      "Infection Control",
      "Pharmacology",
      "Quality Improvement",
    ],
    types: [
      "Live Course", "Enduring Material", "Journal-Based CME", "Internet CME",
      "Performance Improvement CME", "Conference", "Workshop", "Webinar", "Self-Assessment",
    ],
    typicalAnnualHours: 25,
    typicalCycleYears: 2,
  },
  opportunityTypes: [
    "Attending Physician",
    "Hospitalist",
    "Locum Tenens",
    "Academic / Faculty",
    "Fellowship",
    "Residency",
    "Chief Resident",
    "Medical Director",
    "Private Practice",
    "Public Health",
    "Corporate / Industry",
    "Research",
  ],
  renewal: {
    licenseCycleYears: 2,
    deaCycleYears: 3,
    blsCycleYears: 2,
    aclsCycleYears: 2,
    note: "Medical license renewal cycles vary by state board. Many states also require specific CME (e.g. opioid, ethics, patient safety). Each credential record stores its own expiration date and drives reminders.",
  },
  jurisdictions: [
    "AL","AK","AZ","AR","CA","CO","CT","DE","DC","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"
  ],
  membershipOrganizations: [
    "American Medical Association (AMA)",
    "American College of Physicians (ACP)",
    "American College of Surgeons (ACS)",
    "American Academy of Family Physicians (AAFP)",
    "American Academy of Pediatrics (AAP)",
    "American College of Cardiology (ACC)",
    "American College of Emergency Physicians (ACEP)",
    "American Osteopathic Association (AOA)",
    "State Medical Society",
    "Local Medical Society",
  ],
  educationDegrees: [
    "MD", "DO", "MBBS", "PhD", "MPH", "MS", "BS", "BA", "Associate",
  ],
};